# Web4AI Orchestrator Production Configuration
# orchestrator_config_production.yaml

orchestrator:
  id: "web4ai_production_orchestrator"
  port: 9000
  host: "0.0.0.0"
  heartbeat_interval: 30
  task_timeout: 300
  auto_discovery: true
  debug: false
  log_level: "INFO"

network:
  discovery_endpoints:
    - "http://localhost:5000"    # Enhanced Node 1
    - "http://localhost:5001"    # Enhanced Node 2
    - "http://localhost:5002"    # Enhanced Node 3
  max_nodes: 100
  min_nodes: 1
  connection_timeout: 10
  retry_attempts: 3
  retry_delay: 5

performance:
  cpu_threshold: 80
  memory_threshold: 85
  optimization_enabled: true
  load_balancing:
    algorithm: "weighted_round_robin"
    weight_cpu: 0.4
    weight_memory: 0.3
    weight_tasks: 0.3
  health_checks:
    interval: 30
    timeout: 5
    retries: 3

security:
  api_key_required: false
  cors_enabled: true
  rate_limiting: true
  max_requests_per_minute: 100

logging:
  level: "INFO"
  file: "logs/orchestrator.log"
  max_size: "10MB"
  backup_count: 5
  console_output: true

database:
  type: "sqlite"
  path: "data/orchestrator.db"
  backup_enabled: true
  backup_interval: 3600

metrics:
  enabled: true
  prometheus_port: 9090
  collection_interval: 60
